CC = gcc

all: programadesubtração
 comando1 comando2 clean

Compilar: programadesubtraçao.c
	gcc -o programadesubtração
 ./programadesubtração.c

comando1:
  
$nome="João"
	echo "$nome!"
	
ls -la

comando2:
	pwd


clean:
	rm -rf  *.o